### ISSUE TITLE
Libft.h

### ISSUE THREAD

**Issue by ChewyToast** [puyma/libft#31]
Hi @puyma, I don't want to annoy you, I'm just trying to help in this very well organised project so that it continues to scale correctly. Looking at the distribution of the .h files I have doubts why in all the individual .h files inside each folder you still include the libft.h. On the other hand, in the libft.h I see that you include the library "stdlib.h", but I thought I saw that all the functions that require this library have their specific .h file with the library included. Just that, thanks for sharing with us this good work!

**Comment by puyma** [comment]
Hey @ChewyToast, I'm pleased that you took a look at this libft.

It seemed the right thing to do when I was coding it. Now I see it's downright absurd and unnecessary. I'll be working on a fix to this. Cheers.

**Comment by puyma** [comment]
Happy if you want to address any issues that can be improved @ChewyToast.
